language: scala
scala:
  - 2.12.9
jdk:
  - openjdk8
  - openjdk11
services:
  - postgresql
sudo: false

env:
  - TEST_DIR=impure
  - TEST_DIR=pure
  - TEST_DIR=tapir

before_script:
  - psql -c "CREATE ROLE impure WITH LOGIN ENCRYPTED PASSWORD 'secret';" -U postgres
  - psql -c "CREATE DATABASE impure_test WITH OWNER impure;" -U postgres
  - psql -c "CREATE ROLE pure WITH LOGIN ENCRYPTED PASSWORD 'secret';" -U postgres
  - psql -c "CREATE DATABASE pure_test WITH OWNER pure;" -U postgres
  - psql -c "CREATE ROLE tapir WITH LOGIN ENCRYPTED PASSWORD 'secret';" -U postgres
  - psql -c "CREATE DATABASE tapir_test WITH OWNER pure;" -U postgres

script:
  - cd ${TEST_DIR} && sbt clean coverage test it:test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

