language: scala
scala:
  - 2.12.8
jdk:
  - openjdk8

services:
  - postgresql

sudo: false

env:
  - TEST_DIR=impure
  - TEST_DIR=pure

before_script:
  - psql -c "CREATE ROLE impure WITH LOGIN ENCRYPTED PASSWORD 'secret';" -U postgres
  - psql -c "CREATE DATABASE impure_test WITH OWNER impure;" -U postgres
  - psql -c "CREATE ROLE pure WITH LOGIN ENCRYPTED PASSWORD 'secret';" -U postgres
  - psql -c "CREATE DATABASE pure_test WITH OWNER pure;" -U postgres

script:
  - cd ${TEST_DIR} && sbt clean test it:test

